version: '3.8'

services:
  gabaithon-09-back:
    container_name: gabaithon-09-back
    volumes:
      - ./:/gabaithon-09-back
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    command: sh -c 'air'